In [1]:
import sqlite3
import datetime as dt
import pandas as pd
import numpy as np

### Nos conectamos a la base de datos deseada, en caso de que no exista, se creará una nueva base de datos

In [124]:
conn = sqlite3.connect('myDataBase.sqlite')

#### Se descarga el archivo csv donde se encuentran los datos a manipular

In [206]:
datos = pd.read_csv('Produccin.csv')
datos

              Fecha Potencia [kW] Insolación [W/m²]
0    8/28/2020 1:00             x              0.98
1    8/28/2020 2:00             x              0.98
2    8/28/2020 3:00             x              0.98
3    8/28/2020 4:00             x              0.97
4    8/28/2020 5:00             x              0.97
..              ...           ...               ...
163  9/3/2020 20:00             x                 x
164  9/3/2020 21:00             x                 x
165  9/3/2020 22:00             x                 x
166  9/3/2020 23:00             x                 x
167   9/4/2020 0:00             x                 x

[168 rows x 3 columns]

#### Funciones para cambiar nombres de columnas y para eliminar observaciones sin datos de Potencia

In [218]:
def tabla_sencilla(datos):
    datos['Potencia'] = datos['Potencia [kW]']
    datos['Insolacion'] = datos['Insolación [W/m²]']
    datos = datos.drop(['Potencia [kW]', 'Insolación [W/m²]'],axis= "columns")
    datos_limpios(datos)
    return datos

def datos_limpios(datos):
    datos = datos[datos['Potencia']!='x']
    datos['Potencia']=datos['Potencia'].apply(pd.to_numeric)
    datos['Insolacion']=pd.to_numeric(datos['Insolacion'])
    return datos

In [219]:
datos2 = tabla_sencilla(datos)
print(datos,'\n\n', datos2,'\n\n', datos1)

              Fecha Potencia [kW] Insolación [W/m²] Potencia Insolacion
0    8/28/2020 1:00             x              0.98        x       0.98
1    8/28/2020 2:00             x              0.98        x       0.98
2    8/28/2020 3:00             x              0.98        x       0.98
3    8/28/2020 4:00             x              0.97        x       0.97
4    8/28/2020 5:00             x              0.97        x       0.97
..              ...           ...               ...      ...        ...
163  9/3/2020 20:00             x                 x        x          x
164  9/3/2020 21:00             x                 x        x          x
165  9/3/2020 22:00             x                 x        x          x
166  9/3/2020 23:00             x                 x        x          x
167   9/4/2020 0:00             x                 x        x          x

[168 rows x 5 columns]

               Fecha Potencia Insolacion
0    8/28/2020 1:00        x       0.98
1    8/28/2020 2:00        x       0.98
2    8/28/2020 3:00        x       0.98
3    8/28/2020 4:00        x       0.97
4    8/28/2020 5:00        x       0.97
..              ...      ...        ...
163  9/3/2020 20:00        x          x
164  9/3/2020 21:00        x          x
165  9/3/2020 22:00        x          x
166  9/3/2020 23:00        x          x
167   9/4/2020 0:00        x          x

[168 rows x 3 columns]

                Fecha  Potencia  Insolacion
5     8/28/2020 6:00      0.01        1.97
6     8/28/2020 7:00      1.03       23.89
7     8/28/2020 8:00     10.94      231.99
8     8/28/2020 9:00     26.58      522.53
9    8/28/2020 10:00     38.43      722.06
..               ...       ...         ...
149    9/3/2020 6:00      0.00        1.66
150    9/3/2020 7:00      1.27       28.70
151    9/3/2020 8:00     10.95      232.14
152    9/3/2020 9:00     15.33      294.69
153   9/3/2020 10:00     12.07      357.98

[88 rows x 3 columns]

C:\Users\USUARIO\anaconda3\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
C:\Users\USUARIO\anaconda3\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()

#### Se crea una tabla llamada Produccion en la base de datos

In [220]:
try:
    datos1.to_sql('Produccion',con=conn,dtype={'time':'TIMESTAMP'})
except:
    pass

#### Comando que nos muestra las tablas que existen en nuestra base de datos

In [221]:
print(pd.read_sql("SELECT name FROM sqlite_master WHERE type= 'table';",conn))

         name
0  Produccion

#### Comando para leer todas las columnas de la tabla Produccion de nuestra base de datos

In [222]:
df = pd.read_sql("SELECT * FROM Produccion",conn)

In [186]:
df

    index            Fecha  Potencia  Insolacion
0       5   8/28/2020 6:00      0.01        1.97
1       6   8/28/2020 7:00      1.03       23.89
2       7   8/28/2020 8:00     10.94      231.99
3       8   8/28/2020 9:00     26.58      522.53
4       9  8/28/2020 10:00     38.43      722.06
..    ...              ...       ...         ...
83    149    9/3/2020 6:00      0.00        1.66
84    150    9/3/2020 7:00      1.27       28.70
85    151    9/3/2020 8:00     10.95      232.14
86    152    9/3/2020 9:00     15.33      294.69
87    153   9/3/2020 10:00     12.07      357.98

[88 rows x 4 columns]

#### Se pueden obtener datos entre ciertas fechas, el límite superior no se incluye

In [187]:
df = pd.read_sql(
    ("SELECT Fecha, Potencia FROM Produccion WHERE Fecha BETWEEN '9/1/2020' AND '9/3/2020';"),conn)

In [188]:
df

             Fecha  Potencia
0    9/1/2020 6:00      0.00
1    9/1/2020 7:00      1.48
2    9/1/2020 8:00      9.61
3    9/1/2020 9:00     20.48
4   9/1/2020 10:00     32.41
5   9/1/2020 11:00     17.53
6   9/1/2020 12:00     19.60
7   9/1/2020 13:00     25.69
8   9/1/2020 14:00     33.07
9   9/1/2020 15:00     27.45
10  9/1/2020 16:00      7.69
11  9/1/2020 17:00      2.16
12  9/1/2020 18:00      1.87
13  9/1/2020 19:00      0.00
14   9/2/2020 7:00      0.01
15   9/2/2020 8:00      1.37
16   9/2/2020 9:00      5.02
17  9/2/2020 10:00     12.25
18  9/2/2020 11:00     13.72
19  9/2/2020 12:00      4.33
20  9/2/2020 13:00      5.73
21  9/2/2020 14:00      2.68
22  9/2/2020 15:00      4.75
23  9/2/2020 16:00      5.85
24  9/2/2020 17:00      7.51
25  9/2/2020 18:00      1.08
26  9/2/2020 19:00      0.00

#### Se obtienen los datos con una insolación mayor a 90 (Ejemplo específico, no tiene significado alguno)

In [195]:
df2 = pd.read_sql(
    ("SELECT Fecha, Potencia, Insolacion FROM Produccion WHERE Produccion.Insolacion > 90.0;"),conn)

In [197]:
df2

              Fecha  Potencia  Insolacion
0    8/28/2020 8:00     10.94      231.99
1    8/28/2020 9:00     26.58      522.53
2   8/28/2020 10:00     38.43      722.06
3   8/28/2020 11:00     36.25      646.36
4   8/28/2020 12:00     37.88      656.73
5   8/28/2020 13:00     53.12      952.67
6   8/28/2020 14:00     35.07      642.80
7   8/28/2020 15:00     28.59      676.24
8   8/28/2020 16:00     16.12      319.17
9   8/28/2020 17:00      8.78      118.76
10   8/29/2020 8:00     12.04      250.16
11   8/29/2020 9:00     31.04      620.78
12  8/29/2020 10:00     41.86      810.41
13  8/29/2020 11:00     46.29      872.28
14  8/29/2020 12:00     48.82      907.87
15  8/29/2020 13:00     16.31      283.17
16  8/29/2020 14:00     11.29      187.50
17  8/29/2020 15:00      9.03      146.94
18  8/29/2020 16:00      8.95      154.83
19   8/30/2020 9:00     15.02      254.50
20  8/30/2020 10:00     12.21      205.54
21  8/30/2020 11:00     23.25      389.17
22  8/30/2020 12:00     33.71      570.41
23  8/30/2020 13:00     25.48      407.10
24  8/30/2020 14:00     22.38      358.68
25  8/30/2020 15:00      9.06      148.87
26  8/30/2020 16:00     16.30      262.94
27  8/30/2020 17:00      7.03      118.31
28   8/31/2020 8:00     10.36      216.89
29   8/31/2020 9:00     26.50      528.24
30  8/31/2020 10:00     36.99      688.48
31  8/31/2020 11:00     50.58      932.51
32  8/31/2020 12:00     37.07      658.70
33  8/31/2020 13:00     45.29      800.52
34  8/31/2020 14:00     23.16      372.97
35  8/31/2020 15:00     11.47      193.70
36  8/31/2020 16:00      5.51       95.27
37    9/1/2020 8:00      9.61      174.14
38    9/1/2020 9:00     20.48      378.25
39   9/1/2020 10:00     32.41      585.56
40   9/1/2020 11:00     17.53      291.74
41   9/1/2020 12:00     19.60      327.05
42   9/1/2020 13:00     25.69      414.39
43   9/1/2020 14:00     33.07      572.75
44   9/1/2020 15:00     27.45      597.67
45   9/1/2020 16:00      7.69      137.63
46   9/2/2020 10:00     12.25      202.47
47   9/2/2020 11:00     13.72      236.94
48   9/2/2020 13:00      5.73      100.64
49   9/2/2020 16:00      5.85      102.64
50   9/2/2020 17:00      7.51      110.98
51    9/3/2020 8:00     10.95      232.14
52    9/3/2020 9:00     15.33      294.69
53   9/3/2020 10:00     12.07      357.98

### Valores más altos de Insolacion en lo que va de septiembre

#### También se puede obtener los datos más altos o más bajos

In [203]:
altos = """
        SELECT 
            Fecha, Insolacion,Potencia
        FROM 
            Produccion
        WHERE
            Fecha > 9/1/2020
        ORDER BY 
            Insolacion DESC
        LIMIT 
            3
            """
df3 = pd.read_sql(altos,conn)

In [204]:
df3

             Fecha  Insolacion  Potencia
0  8/28/2020 13:00      952.67     53.12
1  8/31/2020 11:00      932.51     50.58
2  8/29/2020 12:00      907.87     48.82

In [ ]:
insertar = """
    INSERT INTO Produccion
    """

In [15]:
df = pd.read_csv('Potencia_solar.csv',header = )

ParserError: Error tokenizing data. C error: Expected 1 fields in line 7, saw 4

In [17]:
df_excel = pd.read_excel('queDatosSirven.xlsx')
df_excel

,Unnamed: 0,¿Exportar?,Día,Semana,Mes,Año
0,Producción de energía,1,1,1,1,1
1,Potencia Solar,1,1,1,1,1
2,Comparación de valores esperados y reales,1,0,0,1,1
3,Pronóstico de rendimiento,1,0,0,0,1
4,Temperatura/Energía,1,1,1,1,1
5,Eficiencia de la planta,0,0,0,0,0
6,Input/output,0,0,0,0,0
7,Índice solar,1,0,0,0,1
8,Mapa de calor inversor,1,1,0,0,0
9,Distrubución de pérdidas,1,0,0,1,1
10,Performance ratio,1,0,0,1,1
11,Índice de potencia,1,1,0,0,0
12,Índice de rendimiento energético,1,0,0,1,1
13,Disponibilidad de plantas,1,0,0,0,1
14,Energía,1,1,1,1,1
15,Energía normalizada,1,1,0,1,1
16,PR inversores,1,1,0,1,0
17,Potencia CA,1,1,1,0,0
18,Potencia CA normalizada,1,1,1,1,1
19,Corriente CA,1,1,1,0,0
20,Tensión CA,1,1,1,0,0
21,Potenica CC,1,1,1,0,0
22,Corriente CC,1,1,1,0,0
23,Corriente CC normalizada,1,1,1,0,0
24,Tensión CC,1,1,1,0,0
25,Tensión CC normalizada,1,1,1,0,0
26,Frecuencia,1,1,1,0,0
27,Temperatura,1,1,1,0,0
28,Resistencia de aislamiento,1,1,1,0,0
29,Coseno phi,1,1,0,1,0
30,Potencia Reactiva,1,1,1,0,0
31,Potencia aparente,1,1,1,0,0
32,Entradas inversores,0,0,0,0,0
33,Corrinete absoluta,1,1,1,0,0
34,Corriente relativa,0,0,0,0,0
35,Mapa de calor corriente de strings,1,1,0,0,0
36,Tensión CC,1,1,1,0,0
37,Radiación,1,1,1,1,1
38,Datos de satélite,1,1,1,1,1