In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import os
f = os.getcwd()
f

'C:\\Users\\USUARIO\\OneDrive\\Universidad\\Proyecto de Grado\\Repositorio\\Proyecto-Electronica\\DATOS SOLAR'

In [16]:
f = os.getcwd()
mes = input('Ingrese el mes: ')
año = input('Ingrese el año: ')

datos = pd.read_csv(f+ '\\'+ mes+' '+año+'.csv',encoding= 'UTF-8',error_bad_lines=False)
datos.head(100)

Ingrese el mes: Febrero
Ingrese el año: 2020

,Fecha,Hora,Potencia [kW],Insolacion [W/m2],Temperatura de modulos [C],Temperatura ambiente [C]
0,1/02/2020,0:00,x,1.00,12.37,12.069304
1,1/02/2020,0:05,x,1.00,12.29,12.064086
2,1/02/2020,0:10,x,1.00,12.16,12.055172
3,1/02/2020,0:15,x,0.99,12.03,12.061572
4,1/02/2020,0:20,x,0.99,11.91,12.098665
...,...,...,...,...,...,...
95,1/02/2020,7:55,2.71,46.48,17.54,15.976952
96,1/02/2020,8:00,3.86,62.87,17.68,15.939789
97,1/02/2020,8:05,4.37,68.35,18.12,15.902893
98,1/02/2020,8:10,3.46,54.62,18.13,15.780109
99,1/02/2020,8:15,3.22,52.05,17.68,15.852241

In [12]:
datos[datos['Temperatura ambiente [C]']==datos['Temperatura ambiente [C]'].max()]

,Fecha,Hora,Potencia [kW],Insolacion [W/m2],Temperatura de modulos [C],Temperatura ambiente [C]
1295,5/12/2019,11:55,61.3,972.52,53.63,29.516811

In [13]:
datos[datos['Hora']=='12:00']

,Fecha,Hora,Potencia [kW],Insolacion [W/m2],Temperatura de modulos [C],Temperatura ambiente [C]
144,1/12/2019,12:00,38.06,463.94,31.05,18.210114
432,2/12/2019,12:00,27.14,322.15,25.36,18.124820
720,3/12/2019,12:00,58.13,841.83,41.03,17.934461
1008,4/12/2019,12:00,77.39,1159.68,48.17,19.708377
1296,5/12/2019,12:00,43.08,621.23,50.00,28.494111
1584,6/12/2019,12:00,61.44,884.04,41.96,24.959414
1872,7/12/2019,12:00,30.49,394.21,41.08,24.202102
2160,8/12/2019,12:00,37.86,471.80,29.06,22.219364
2448,9/12/2019,12:00,57.76,882.52,45.74,20.376500
2736,10/12/2019,12:00,32.8,468.44,36.01,22.067439
3024,11/12/2019,12:00,14.54,198.18,36.74,24.718561
3312,12/12/2019,12:00,63.05,934.15,44.94,23.370002
3600,13/12/2019,12:00,20.76,276.62,27.85,21.859255
3888,14/12/2019,12:00,1.97,38.62,13.00,12.426225
4176,15/12/2019,12:00,18.05,216.57,28.38,21.082355
4464,16/12/2019,12:00,29.63,429.15,34.44,15.727668
4752,17/12/2019,12:00,49.01,672.53,35.14,23.485825
5040,18/12/2019,12:00,19.45,264.33,26.73,21.433877
5328,19/12/2019,12:00,12.55,166.29,25.76,19.676980
5616,20/12/2019,12:00,31.55,444.57,43.42,24.485530
5904,21/12/2019,12:00,19.03,252.34,28.24,21.625257
6192,22/12/2019,12:00,43.57,594.60,36.61,17.407386
6480,23/12/2019,12:00,15.72,196.99,26.20,18.829495
6768,24/12/2019,12:00,32.21,439.01,36.84,21.696111
7056,25/12/2019,12:00,22.99,303.53,28.73,20.196327
7344,26/12/2019,12:00,28.75,383.41,29.26,21.711066
7632,27/12/2019,12:00,14.9,198.67,23.88,19.649086
7920,28/12/2019,12:00,48.82,676.94,47.26,23.107873
8208,29/12/2019,12:00,44.66,642.76,38.91,18.785309
8496,30/12/2019,12:00,13.74,186.27,26.73,23.526786
8784,31/12/2019,12:00,60.31,832.50,37.83,25.070264